---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wuxin.
--- DateTime: 2019-11-14 18:12
---



local kong = kong


local ejuaeskey={}
ejuaeskey.PRIORITY=200
ejuaeskey.VERSION="1.0"



function ejuaeskey:header_filter(conf)
    -- 清空header中的content-length
    ngx.header.content_length=nil

end

function ejuaeskey:access(conf)


    if ngx.ctx.eju_dont_do_anything then
        return
    end

    ngx.ctx.eju_dont_do_anything = true
    return kong.response.exit(ngx.HTTP_OK,conf.key)

end


return ejuaeskey